<?php
/** Admin-only queue for refunds escalated after a hotel misses its SLA. */
if (session_status() === PHP_SESSION_NONE) session_start();
$baseUrl='/travelix';
if (empty($_SESSION['user']['uid'])) { header('Location: '.$baseUrl.'/auth/login.php'); exit; }
if (strtolower((string)($_SESSION['user']['role']??''))!=='admin') { header('Location: '.$baseUrl.'/dashboard/admin_dashboard.php'); exit; }
require_once $_SERVER['DOCUMENT_ROOT'].$baseUrl.'/config/firebase_config.php';
require_once $_SERVER['DOCUMENT_ROOT'].$baseUrl.'/includes/firestore_admin.php';
require_once $_SERVER['DOCUMENT_ROOT'].$baseUrl.'/includes/commission_lib.php';
$sa=$_SERVER['DOCUMENT_ROOT'].$baseUrl.'/config/firebase-service-account.json';
$all=hp_firestore_query($sa,FIREBASE_PROJECT_ID,'hotel_bookings');
$refunds=array_values(array_filter($all,fn($b)=>strtolower((string)($b['bookingStatus']??''))==='cancelled'&&strtolower((string)($b['refundStatus']??''))==='escalated'&&strtolower((string)($b['refundOwner']??'admin'))==='admin'));
usort($refunds,fn($a,$b)=>(float)($a['refundEscalatedAt']??$a['refundRequestedAt']??0)<=>(float)($b['refundEscalatedAt']??$b['refundRequestedAt']??0));
$total=array_sum(array_map(fn($b)=>(float)($b['refundAmount']??0),$refunds));
foreach($refunds as &$row){$uid=(string)($row['uid']??$row['userId']??'');$u=$uid!==''?hp_firestore_get($sa,FIREBASE_PROJECT_ID,'users/'.$uid):[];$snap=is_array($row['refundAccountSnapshot']??null)?$row['refundAccountSnapshot']:[];$row['_method']=(string)($snap['method']??$u['paymentMethod']??'');$row['_bank']=(string)($snap['bankName']??$u['bankName']??'');$row['_account']=(string)($snap['accountNumber']??$u['paymentAccountNumber']??'');}unset($row);
function rh($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Escalated Refunds — Travelix Admin</title>
<link rel="stylesheet" href="/travelix/assets/vendor/bootstrap.min.css"><link rel="stylesheet" href="/travelix/assets/vendor/fontawesome/all.min.css"><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<style>*{box-sizing:border-box}body{margin:0;background:#f0f4fa;font-family:Segoe UI,sans-serif}.admin-page{display:flex;gap:24px;padding:16px;min-height:100vh}.admin-content{flex:1;min-width:0;padding:16px}.hero{background:linear-gradient(135deg,#b91c1c,#ef4444);color:#fff;padding:27px 30px;border-radius:22px;margin-bottom:22px;display:flex;justify-content:space-between;align-items:center;gap:18px}.hero h1{font-size:25px;font-weight:900;margin:0}.hero p{margin:5px 0 0;opacity:.9}.hero-total{text-align:right;white-space:nowrap}.hero-total strong{display:block;font-size:27px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:20px;box-shadow:0 8px 28px #0f172a12;overflow:hidden}.card-head{padding:20px 24px;border-bottom:1px solid #e5e7eb}.refund-row{display:grid;grid-template-columns:minmax(220px,1fr) minmax(220px,1fr) auto auto;align-items:center;gap:18px;padding:19px 24px;border-bottom:1px solid #eef2f7}.refund-row:last-child{border-bottom:0}.name{font-weight:900;color:#0f172a}.sub{font-size:12px;color:#64748b;margin-top:3px}.amount{font-size:19px;font-weight:900;color:#dc2626;white-space:nowrap}.send{border:0;border-radius:11px;background:#dcfce7;color:#166534;padding:11px 16px;font-weight:800;cursor:pointer}.empty{text-align:center;padding:55px;color:#94a3b8}@media(max-width:900px){.admin-page{display:block;padding:0}.admin-content{padding:14px}.refund-row{grid-template-columns:1fr}.hero{align-items:flex-start;flex-direction:column}.hero-total{text-align:left}}</style></head><body>
<div class="admin-page"><?php include $_SERVER['DOCUMENT_ROOT'].$baseUrl.'/includes/admin_sidebar.php'; ?><main class="admin-content"><section class="hero"><div><h1><i class="fas fa-shield-halved"></i> Escalated Refunds</h1><p>Only refunds the hotel failed to complete within its SLA appear here. Travelix pays the guest and keeps the hotel disabled for review.</p></div><div class="hero-total"><span><?= count($refunds) ?> pending</span><strong><?= hp_money($total) ?></strong></div></section>
<section class="card"><div class="card-head"><h2 style="font-size:18px;font-weight:900;margin:0">Travelix Must Pay These Guests</h2><p style="font-size:13px;color:#64748b;margin:4px 0 0">Use the guest's saved refund account and attach proof before recording the transfer.</p></div>
<?php if(!$refunds):?><div class="empty"><div style="font-size:42px">✅</div><strong>No escalated refunds</strong><div>Hotels are currently handling their refunds within the allowed time.</div></div><?php else:foreach($refunds as $b):?>
<div class="refund-row"><div><div class="name"><?= rh($b['userEmail']??'Guest') ?></div><div class="sub"><?= rh($b['hotelName']??'Hotel') ?> · Booking <?= rh($b['id']) ?></div></div><div><div class="name"><?= rh(ucfirst($b['_method']).($b['_bank']?' · '.$b['_bank']:'')) ?></div><div class="sub" style="font-family:monospace"><?= rh($b['_account']?:'Refund account missing') ?></div></div><div class="amount"><?= hp_money($b['refundAmount']??0) ?></div><button class="send" onclick='sendRefund(<?= json_encode((string)$b['id']) ?>,<?= json_encode((string)($b['userEmail']??'Guest')) ?>)'><i class="fas fa-paper-plane"></i> Pay With Proof</button></div>
<?php endforeach;endif;?></section></main></div>
<script>
async function sendRefund(bookingId,guest){const ask=await Swal.fire({title:'Send escalated refund',html:`Confirm you paid <b>${guest}</b> using the account shown, then upload transfer proof.`,input:'file',inputAttributes:{accept:'.jpg,.jpeg,.png,.webp,.pdf'},showCancelButton:true,confirmButtonText:'Upload Proof & Record',confirmButtonColor:'#16a34a',preConfirm:f=>{if(!f){Swal.showValidationMessage('Transfer proof is required.');return false}return f}});if(!ask.isConfirmed)return;try{Swal.fire({title:'Uploading proof...',showConfirmButton:false,allowOutsideClick:false,didOpen:()=>Swal.showLoading()});const fd=new FormData();fd.append('proof',ask.value);const ur=await fetch('/travelix/admin_manage/ajax/upload_transfer_proof.php',{method:'POST',body:fd,credentials:'same-origin'});const up=await ur.json();if(!up.success)throw new Error(up.message||'Proof upload failed');const rr=await fetch('/travelix/admin_manage/ajax/mark_refund_sent.php',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({bookingId,proofPath:up.path})});const data=await rr.json();if(!data.success)throw new Error(data.message||'Could not record refund');await Swal.fire({icon:'success',title:'Refund Sent',text:data.message,confirmButtonColor:'#133c96'});location.reload()}catch(e){Swal.fire({icon:'error',title:'Failed',text:e.message,confirmButtonColor:'#133c96'})}}
</script></body></html>
