<?php
/**
 * Generates a branded Trip Itinerary PDF for a saved trip document.
 * Pure FPDF (no GD needed) — self-hosted at assets/vendor/fpdf/fpdf.php.
 */

require_once $_SERVER['DOCUMENT_ROOT'] . '/travelix/assets/vendor/fpdf/fpdf.php';

class TravelixTripPdf extends FPDF
{
    private $logoPath;

    const BRAND      = [15, 52, 96];
    const BRAND_SOFT  = [235, 243, 250];
    const ACCENT      = [20, 132, 180];
    const TEXT_DARK   = [30, 30, 30];
    const TEXT_MUTED  = [110, 118, 130];
    const BORDER      = [225, 231, 238];

    public function __construct($logoPath)
    {
        parent::__construct('P', 'mm', 'A4');
        $this->logoPath = $logoPath;
        $this->SetMargins(15, 15, 15);
        $this->SetAutoPageBreak(true, 22);
    }

    public function Header()
    {
        if (file_exists($this->logoPath)) {
            $this->Image($this->logoPath, 15, 12, 42);
        }

        $this->SetFont('Helvetica', '', 9);
        $this->SetTextColor(...self::TEXT_MUTED);
        $this->SetXY(-65, 16);
        $this->Cell(50, 6, 'Trip Itinerary', 0, 0, 'R');

        $this->SetY(30);
        $this->SetDrawColor(...self::ACCENT);
        $this->SetLineWidth(0.6);
        $this->Line(15, 30, 195, 30);
        $this->Ln(8);
    }

    public function Footer()
    {
        $this->SetY(-18);
        $this->SetDrawColor(...self::BORDER);
        $this->SetLineWidth(0.2);
        $this->Line(15, $this->GetY(), 195, $this->GetY());
        $this->Ln(2);
        $this->SetFont('Helvetica', 'I', 8);
        $this->SetTextColor(...self::TEXT_MUTED);
        $this->Cell(0, 8, 'Generated by Travelix - travelix.buzz', 0, 0, 'L');
        $this->Cell(0, 8, 'Page ' . $this->PageNo(), 0, 0, 'R');
    }

    public function sectionTitle($title)
    {
        $this->checkSpace(16);
        $this->SetFillColor(...self::ACCENT);
        $this->SetY($this->GetY() + 1);
        $this->Rect($this->GetX(), $this->GetY(), 3, 6, 'F');
        $this->SetX($this->GetX() + 6);
        $this->SetFont('Helvetica', 'B', 13);
        $this->SetTextColor(...self::BRAND);
        $this->Cell(0, 8, $this->clean($title), 0, 1, 'L');
        $this->Ln(2);
    }

    public function keyValueRow($label, $value)
    {
        $this->checkSpace(9);
        $this->SetFillColor(...self::BRAND_SOFT);
        $this->SetFont('Helvetica', 'B', 9.5);
        $this->SetTextColor(90, 90, 90);
        $this->Cell(55, 8, ' ' . $this->clean($label), 0, 0, 'L', true);

        $this->SetFont('Helvetica', '', 9.5);
        $this->SetTextColor(...self::TEXT_DARK);
        $x = $this->GetX();
        $y = $this->GetY();
        $this->SetXY($x + 2, $y + 1.2);
        $this->MultiCell(133, 5.6, $this->clean($value ?: '-'));
        if ($this->GetY() < $y + 8) {
            $this->SetY($y + 8);
        }
    }

    public function bodyText($text)
    {
        $this->checkSpace(10);
        $this->SetFont('Helvetica', '', 10.5);
        $this->SetTextColor(60, 60, 60);
        $this->MultiCell(0, 6.5, $this->clean($text));
    }

    /** Ensures at least $mm of vertical room before the auto page-break margin; forces a new page otherwise. */
    public function checkSpace($mm)
    {
        if ($this->GetY() + $mm > $this->PageBreakTrigger) {
            $this->AddPage();
        }
    }

    /**
     * Renders a table with a header row and simple alternating-row shading.
     * $rows: list of associative arrays matching $columns keys.
     * $columns: [key => [label, width]]
     */
    public function dataTable(array $columns, array $rows)
    {
        $this->checkSpace(14);

        $this->SetFont('Helvetica', 'B', 9);
        $this->SetTextColor(255, 255, 255);
        $this->SetFillColor(...self::ACCENT);
        foreach ($columns as $col) {
            $this->Cell($col[1], 8, $this->clean($col[0]), 0, 0, 'C', true);
        }
        $this->Ln();

        $this->SetFont('Helvetica', '', 9);
        $rowIndex = 0;
        foreach ($rows as $row) {
            $this->checkSpace(8);
            $fill = ($rowIndex % 2 === 0) ? [255, 255, 255] : self::BRAND_SOFT;
            $this->SetFillColor(...$fill);
            $this->SetTextColor(...self::TEXT_DARK);
            foreach ($columns as $key => $col) {
                $this->Cell($col[1], 7.5, $this->clean($row[$key] ?? '-'), 0, 0, 'C', true);
            }
            $this->Ln();
            $rowIndex++;
        }
        $this->Ln(4);
    }

    /** A single place card: thumbnail (if a real file is found) + name + short description. */
    public function placeCard($order, $name, $description, $imageAbsPath)
    {
        $imgW = 26;
        $textX = $this->lMargin;
        $hasImage = false;
        $imgH = 0;

        if ($imageAbsPath && file_exists($imageAbsPath)) {
            $size = @getimagesize($imageAbsPath);
            if ($size) {
                $imgH = $imgW * ($size[1] / $size[0]);
                $imgH = min($imgH, 26);
                $hasImage = true;
            }
        }

        // Estimate the card's height up-front (title line + wrapped description) so we can page-break cleanly.
        $descLines = $description !== '' ? ceil($this->GetStringWidth($this->clean($description)) / 150) + 1 : 1;
        $estHeight = max($hasImage ? $imgH : 0, 8 + ($descLines * 5)) + 6;
        $this->checkSpace($estHeight);

        $topY = $this->GetY();

        if ($hasImage) {
            $this->Image($imageAbsPath, $this->lMargin, $topY, $imgW, $imgH);
            $textX = $this->lMargin + $imgW + 6;
        }

        $textW = 180 - ($textX - $this->lMargin);

        $this->SetXY($textX, $topY);
        $this->SetFont('Helvetica', 'B', 11);
        $this->SetTextColor(...self::BRAND);
        $this->Cell($textW, 6.5, $this->clean($order . '. ' . $name), 0, 1);

        $this->SetX($textX);
        $this->SetFont('Helvetica', '', 9.5);
        $this->SetTextColor(90, 90, 90);
        $desc = $description !== '' ? $description : 'A recommended stop on this itinerary.';
        if (mb_strlen($desc) > 260) {
            $desc = mb_substr($desc, 0, 257) . '...';
        }
        $this->MultiCell($textW, 5.2, $this->clean($desc));

        $bottomY = max($this->GetY(), $topY + $imgH);
        $this->SetY($bottomY + 5);

        $this->SetDrawColor(...self::BORDER);
        $this->SetLineWidth(0.15);
        $this->Line($this->lMargin, $this->GetY(), 195, $this->GetY());
        $this->Ln(4);
    }

    /** Closing branded "thank you" box shown at the end of the itinerary. */
    public function thankYouBox($destination)
    {
        $this->checkSpace(30);
        $this->Ln(2);

        $y = $this->GetY();
        $this->SetFillColor(...self::BRAND);
        $this->Rect($this->lMargin, $y, 180, 28, 'F');

        $this->SetXY($this->lMargin, $y + 6);
        $this->SetFont('Helvetica', 'B', 14);
        $this->SetTextColor(255, 255, 255);
        $this->Cell(180, 8, 'Thank you for planning with Travelix!', 0, 1, 'C');

        $this->SetX($this->lMargin);
        $this->SetFont('Helvetica', '', 10);
        $this->SetTextColor(224, 238, 247);
        $message = $destination
            ? "We hope you have a wonderful trip to {$destination}. Come back soon for your next adventure!"
            : 'We hope you have a wonderful trip. Come back soon for your next adventure!';
        $this->Cell(180, 7, $this->clean($message), 0, 1, 'C');

        $this->SetY($y + 28 + 6);
    }

    /** FPDF's built-in fonts only support Windows-1252 — sanitize UTF-8 input safely. */
    public function clean($text)
    {
        $text = (string)$text;
        $converted = $text;

        if (function_exists('iconv')) {
            // //TRANSLIT still emits a literal "?" for every character it can't
            // approximate (e.g. Urdu/Arabic script — FPDF's core fonts only
            // support CP1252), which is exactly the "???" garbling this was
            // reported for. //IGNORE alone silently drops those characters
            // instead of leaving visible junk behind.
            $attempt = @iconv('UTF-8', 'CP1252//IGNORE', $text);
            if ($attempt !== false) $converted = $attempt;
        } else {
            $converted = preg_replace('/[^\x20-\x7E]/', '', $text);
        }

        // Dropping a script mid-string can leave orphaned punctuation/whitespace
        // behind (e.g. "G7), " with nothing after the comma) — tidy that up.
        // Only collapse spaces/tabs, not newlines, so multi-line notes keep
        // their line breaks.
        $converted = preg_replace('/[ \t]+/', ' ', $converted);
        $converted = preg_replace('/,[ \t]*(?=[,.]|$)/m', '', $converted);
        return trim($converted);
    }
}

/** Resolves a trip-stored image path (e.g. "/travelix/images/x.jpg") to a local filesystem path. */
/**
 * Resolves a place's saved image reference to a local filesystem path.
 * Places can end up with the image saved in slightly different shapes
 * depending on where they were selected from (admin-added city, static
 * destination data, a full URL, etc.) — this normalizes all of them instead
 * of only accepting an exact "/travelix/..." prefix, which silently dropped
 * a place's image (no error, just no picture in the PDF) whenever the saved
 * path didn't match that one exact shape.
 */
function travelix_pdf_local_path($webPath)
{
    $webPath = trim((string)$webPath);
    if ($webPath === '') return '';

    // A full URL — keep only the path part.
    if (preg_match('#^https?://[^/]+(/.*)$#i', $webPath, $m)) {
        $webPath = $m[1];
    }

    if (strpos($webPath, '/travelix/') === 0) {
        return $_SERVER['DOCUMENT_ROOT'] . $webPath;
    }

    // Site-relative but missing the /travelix prefix (e.g. "/images/x.jpg").
    if ($webPath[0] === '/') {
        return $_SERVER['DOCUMENT_ROOT'] . '/travelix' . $webPath;
    }

    // A bare filename with no leading slash at all.
    return $_SERVER['DOCUMENT_ROOT'] . '/travelix/images/' . ltrim($webPath, '/');
}

/** Parses the pipe-separated weatherSummary string into table rows. */
function travelix_pdf_parse_weather($summary)
{
    $rows = [];
    $segments = array_filter(array_map('trim', explode('|', (string)$summary)));

    foreach ($segments as $segment) {
        if (preg_match('/^(\S+):\s*max\s*([\-\d.]+)C,\s*min\s*([\-\d.]+)C,\s*rain\s*(\d+)%$/i', $segment, $m)) {
            $rows[] = [
                'date' => $m[1],
                'max'  => $m[2] . ' C',
                'min'  => $m[3] . ' C',
                'rain' => $m[4] . '%',
            ];
        }
    }

    return $rows;
}

/**
 * Builds the itinerary PDF for one trip document and returns the raw PDF
 * bytes (does not write to disk or send anything).
 *
 * $userProfile (optional): ['firstName', 'lastName', 'email', 'phone'] of the
 * trip's owner, used for the User Details section.
 */
function travelix_generate_trip_pdf(array $trip, array $userProfile = []): string
{
    $logoPath = $_SERVER['DOCUMENT_ROOT'] . '/travelix/images/logo.png';
    $pdf = new TravelixTripPdf($logoPath);
    $pdf->AddPage();

    $destination = (string)($trip['destination'] ?? $trip['toCity'] ?? 'Your Trip');

    $pdf->SetFont('Helvetica', 'B', 22);
    $pdf->SetTextColor(...TravelixTripPdf::BRAND);
    $pdf->Cell(0, 12, $pdf->clean($destination), 0, 1);

    $created = $trip['createdAt'] ?? null;
    if (is_string($created) && $created !== '') {
        $ts = strtotime($created);
        if ($ts) {
            $pdf->SetFont('Helvetica', '', 9.5);
            $pdf->SetTextColor(140, 140, 140);
            $pdf->Cell(0, 7, 'Saved on ' . date('d M Y', $ts), 0, 1);
        }
    }
    $pdf->Ln(3);

    // ── Traveler Details ──
    $fullName = trim((string)($userProfile['firstName'] ?? '') . ' ' . (string)($userProfile['lastName'] ?? ''));
    $email = (string)($userProfile['email'] ?? $trip['userEmail'] ?? '');
    $phone = (string)($userProfile['phone'] ?? '');

    if ($fullName !== '' || $email !== '') {
        $pdf->sectionTitle('Traveler Details');
        if ($fullName !== '') $pdf->keyValueRow('Name:', $fullName);
        if ($email !== '') $pdf->keyValueRow('Email:', $email);
        if ($phone !== '') $pdf->keyValueRow('Phone:', $phone);
        $pdf->Ln(3);
    }

    // ── Trip Details ──
    $pdf->sectionTitle('Trip Details');
    $pdf->keyValueRow('Dates:', trim(($trip['arrivalDate'] ?? '') . ' to ' . ($trip['departureDate'] ?? '')));
    $pdf->keyValueRow('Travellers:', $trip['travelers'] ?? '');
    $pdf->keyValueRow('Budget:', $trip['budget'] ?? '');
    $pdf->keyValueRow('Private Car:', $trip['privateCar'] ?? '');
    $pdf->keyValueRow('Estimated Budget:', $trip['estimatedBudget'] ?? '');
    if (!empty($trip['suggestedTransport'])) {
        $pdf->keyValueRow('Suggested Transport:', $trip['suggestedTransport']);
    }
    $pdf->Ln(3);

    // ── Hotel ──
    $bookedHotel = $trip['bookedHotel'] ?? null;
    $pdf->sectionTitle('Hotel');
    if (is_array($bookedHotel) && !empty($bookedHotel['hotelName'])) {
        $pdf->keyValueRow('Hotel Name:', $bookedHotel['hotelName']);
        if (!empty($bookedHotel['roomType'])) {
            $pdf->keyValueRow('Room Type:', $bookedHotel['roomType']);
        }
        if (!empty($bookedHotel['hotelAddress'])) {
            $pdf->keyValueRow('Address:', $bookedHotel['hotelAddress']);
        }
        if (!empty($bookedHotel['arrivalDate']) || !empty($bookedHotel['departureDate'])) {
            $pdf->keyValueRow('Check-in / Check-out:', trim(($bookedHotel['arrivalDate'] ?? '') . ' to ' . ($bookedHotel['departureDate'] ?? '')));
        }
        $bookedHotelTotal = $bookedHotel['totalCharged'] ?? $bookedHotel['hotelPrice'] ?? '';
        if ($bookedHotelTotal !== '') {
            $pdf->keyValueRow('Total Paid:', 'PKR ' . number_format((float)$bookedHotelTotal));
        }
    } elseif (($trip['hotelOption'] ?? '') === 'No') {
        $pdf->bodyText('No hotel was booked for this trip.');
    } else {
        $pdf->bodyText((string)($trip['suggestedHotel'] ?? 'Not specified.'));
    }
    $pdf->Ln(3);

    // ── Selected Places ──
    $places = $trip['selectedPlaces'] ?? [];
    if (is_array($places) && count($places)) {
        $pdf->sectionTitle('Places To Visit');
        foreach ($places as $i => $place) {
            $name = is_array($place) ? ($place['name'] ?? '') : (string)$place;
            if ($name === '') continue;

            $description = is_array($place) ? (string)($place['description'] ?? '') : '';
            $imagePath = is_array($place) ? travelix_pdf_local_path($place['image'] ?? '') : '';

            $pdf->placeCard($i + 1, $name, $description, $imagePath);
        }
        $pdf->Ln(1);
    }

    // ── Weather ──
    $weatherRows = travelix_pdf_parse_weather($trip['weatherSummary'] ?? '');
    if (!empty($weatherRows)) {
        $pdf->sectionTitle('Weather Summary');
        $pdf->dataTable(
            [
                'date' => ['Date', 45],
                'max'  => ['Max Temp', 45],
                'min'  => ['Min Temp', 45],
                'rain' => ['Rain Chance', 45],
            ],
            $weatherRows
        );
    } elseif (!empty($trip['weatherSummary'])) {
        $pdf->sectionTitle('Weather Summary');
        $pdf->bodyText($trip['weatherSummary']);
        $pdf->Ln(3);
    }

    // ── Notes ──
    if (!empty($trip['tripNotes'])) {
        $pdf->sectionTitle('Trip Notes');
        $pdf->bodyText($trip['tripNotes']);
        $pdf->Ln(3);
    }

    // ── Closing ──
    $pdf->thankYouBox($destination);

    return $pdf->Output('S');
}
